name: notes
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^4.0.5555

  firebase_core: ^0.5.2
  firebase_database: ^4.3.0
  cloud_firestore: ^0.14.4

  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6

  flutter_bloc: ^6.1.1
  equatable: ^0.2.0
  meta: ^1.1.6
  intl: ^0.16.1
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher.png" # only available for Android 8.0 devices and above
  adaptive_icon_background: "assets/ic_background.png" # only available for Android 8.0 devices and above

flutter:

  assets:
    - assets/
